import { errorResponse } from "../../../_auth";
import { DELETE_ORDER, TABLE_COLUMNS } from "../_backup_schema";

export { DELETE_ORDER, TABLE_COLUMNS };

export function pick(obj: any, cols: string[]) {
  return cols.map((c) => (obj?.[c] === undefined ? null : obj[c]));
}

export function nowIso() {
  return new Date().toISOString();
}

export function parseJsonSafe<T = any>(raw: string | null | undefined, fallback: T): T {
  if (raw == null || raw === "") return fallback;
  try {
    return JSON.parse(String(raw)) as T;
  } catch {
    return fallback;
  }
}

// multipart helpers
export function isLikelyGzipFilename(name: string) {
  const n = (name || "").toLowerCase();
  return n.endsWith(".gz") || n.endsWith(".gzip");
}

function isGzipMagicBytes(bytes?: Uint8Array | null) {
  return !!bytes && bytes.length >= 2 && bytes[0] === 0x1f && bytes[1] === 0x8b;
}

export async function sniffGzipFromFile(file: File) {
  try {
    const ab = await file.slice(0, 2).arrayBuffer();
    return isGzipMagicBytes(new Uint8Array(ab));
  } catch {
    // Fallback to filename when slice/arrayBuffer is not available.
    return isLikelyGzipFilename((file as any)?.name || "");
  }
}

/**
 * Read the first chunk of a stream to detect gzip magic bytes, then return a new stream that
 * replays that chunk + the rest of the original stream.
 */
export async function sniffGzipFromStream(stream: ReadableStream<Uint8Array>) {
  const reader = stream.getReader();
  const first = await reader.read();
  const firstChunk = first?.value;
  const gzip = isGzipMagicBytes(firstChunk);

  const replay = new ReadableStream<Uint8Array>({
    start(controller) {
      if (firstChunk && firstChunk.length) controller.enqueue(firstChunk);
      const pump = () => {
        reader.read().then(({ value, done }) => {
          if (done) {
            controller.close();
            return;
          }
          if (value) controller.enqueue(value);
          pump();
        }).catch((err) => controller.error(err));
      };
      pump();
    },
    cancel(reason) {
      try { reader.cancel(reason); } catch {}
    }
  });

  return { stream: replay, gzip };
}

export async function* textChunksFromFile(file: File, forceGzip?: boolean) {
  let s: ReadableStream<Uint8Array> = file.stream();

  // Do NOT rely on filename to decide gzip; browsers may transparently decompress downloads.
  const wantGzip = (typeof forceGzip === "boolean") ? forceGzip : await sniffGzipFromFile(file);

  if (wantGzip) {
    if (typeof (globalThis as any).DecompressionStream === "undefined") {
      throw new Error("当前环境不支持 gzip 解压，请上传 .json 备份或在支持 DecompressionStream 的环境中操作");
    }
    s = s.pipeThrough(new DecompressionStream("gzip"));
  }

  const decoder = new TextDecoderStream();
  const reader = s.pipeThrough(decoder).getReader();
  try {
    while (true) {
      const { value, done } = await reader.read();
      if (done) break;
      if (value) yield value;
    }
  } finally {
    reader.releaseLock();
  }
}

// Same streaming row iterator as restore_upload.ts, yielding per-row JSON text.
// NOTE: this parser assumes the backup is generated by this project (tables object, arrays of objects).
export async function* iterBackupRows(file: File): AsyncGenerator<{ table: string; rowText: string }, void, unknown> {
  const skipWS = (buf: string, i: number) => {
    while (i < buf.length) {
      const c = buf[i];
      if (c === " " || c === "\n" || c === "\r" || c === "\t") i++;
      else break;
    }
    return i;
  };

  const readJsonString = (buf: string, i: number) => {
    i++; // skip opening quote
    let out = "";
    let esc = false;
    while (i < buf.length) {
      const c = buf[i++];
      if (esc) {
        out += c;
        esc = false;
        continue;
      }
      if (c === "\\") {
        out += c;
        esc = true;
        continue;
      }
      if (c === '"') {
        return { value: JSON.parse(`"${out}"`), next: i };
      }
      out += c;
    }
    return null;
  };

  let buf = "";
  let state: "seek_tables" | "seek_table_key" | "seek_array_start" | "in_array" = "seek_tables";
  let curTable = "";

  let objStart = -1;
  let depth = 0;
  let objInString = false;
  let objEscape = false;

  // We accept .json OR .json.gz; if gzip not supported, user should upload plain json.
  for await (const chunk of textChunksFromFile(file)) {
    buf += chunk;
    let i = 0;

    while (i < buf.length) {
      if (state === "seek_tables") {
        const idx = buf.indexOf('"tables"', i);
        if (idx === -1) {
          buf = buf.slice(Math.max(0, buf.length - 64));
          i = 0;
          break;
        }
        i = idx + '"tables"'.length;
        i = skipWS(buf, i);
        if (buf[i] !== ":") { i++; continue; }
        i++;
        i = skipWS(buf, i);
        if (buf[i] !== "{") { i++; continue; }
        i++;
        state = "seek_table_key";
        continue;
      }

      if (state === "seek_table_key") {
        i = skipWS(buf, i);
        if (i >= buf.length) break;
        if (buf[i] === "}") return;
        if (buf[i] === ",") { i++; continue; }
        if (buf[i] !== '"') { i++; continue; }

        const r = readJsonString(buf, i);
        if (!r) break;
        curTable = r.value;
        i = r.next;
        state = "seek_array_start";
        continue;
      }

      if (state === "seek_array_start") {
        i = skipWS(buf, i);
        if (i >= buf.length) break;
        if (buf[i] !== ":") { i++; continue; }
        i++;
        i = skipWS(buf, i);
        if (i >= buf.length) break;
        if (buf[i] !== "[") { i++; continue; }
        i++;
        state = "in_array";
        objStart = -1;
        depth = 0;
        objInString = false;
        objEscape = false;
        continue;
      }

      if (state === "in_array") {
        i = skipWS(buf, i);
        if (i >= buf.length) break;

        const c = buf[i];

        if (objStart === -1) {
          if (c === "]") {
            i++;
            state = "seek_table_key";
            continue;
          }
          if (c === ",") { i++; continue; }
          if (c === "{") {
            objStart = i;
            depth = 0;
            objInString = false;
            objEscape = false;
          } else {
            i++;
            continue;
          }
        }

        for (; i < buf.length; i++) {
          const ch = buf[i];

          if (objInString) {
            if (objEscape) {
              objEscape = false;
              continue;
            }
            if (ch === "\\") {
              objEscape = true;
              continue;
            }
            if (ch === '"') {
              objInString = false;
              continue;
            }
            continue;
          } else {
            if (ch === '"') {
              objInString = true;
              continue;
            }
            if (ch === "{") depth++;
            if (ch === "}") {
              depth--;
              if (depth === 0) {
                const rowText = buf.slice(objStart, i + 1);
                yield { table: curTable, rowText };
                objStart = -1;
                i++; // past }
                break;
              }
            }
          }
        }

        if (objStart !== -1) {
          buf = buf.slice(objStart);
          i = 0;
          objStart = 0;
          break;
        }

        if (i > 4096) {
          buf = buf.slice(i);
          i = 0;
        }
        continue;
      }

      i++;
    }
  }
}


export async function* textChunksFromStream(stream: ReadableStream<Uint8Array>, gzip?: boolean) {
  let s: ReadableStream<Uint8Array> = stream;
  if (gzip && typeof (globalThis as any).DecompressionStream !== "undefined") {
    s = s.pipeThrough(new DecompressionStream("gzip"));
  }
  const decoder = new TextDecoderStream();
  const reader = s.pipeThrough(decoder).getReader();
  try {
    while (true) {
      const { value, done } = await reader.read();
      if (done) break;
      if (value) yield value;
    }
  } finally {
    reader.releaseLock();
  }
}

// Read top-level "stats" object from a backup json stream (v2), without parsing the full file.
// Brace-balanced so it works even when chunks split in the middle.
export async function readBackupStatsFromStream(stream: ReadableStream<Uint8Array>, gzip?: boolean): Promise<Record<string, number> | null> {
  let buf = "";
  let found = false;
  let started = false;
  let depth = 0;
  let inStr = false;
  let esc = false;
  let objStart = -1;

  for await (const chunk of textChunksFromStream(stream, gzip)) {
    buf += chunk;

    if (!found) {
      const idx = buf.indexOf('"stats"');
      if (idx === -1) {
        buf = buf.slice(Math.max(0, buf.length - 256));
        continue;
      }
      found = true;
      buf = buf.slice(idx);
    }

    if (!started) {
      const colon = buf.indexOf(':');
      if (colon === -1) continue;
      const brace = buf.indexOf('{', colon);
      if (brace === -1) continue;
      started = true;
      objStart = brace;
      depth = 0;
      inStr = false;
      esc = false;
    }

    for (let i = objStart; i < buf.length; i++) {
      const ch = buf[i];
      if (inStr) {
        if (esc) { esc = false; continue; }
        if (ch === '\\') { esc = true; continue; }
        if (ch === '"') { inStr = false; continue; }
        continue;
      }
      if (ch === '"') { inStr = true; continue; }
      if (ch === '{') depth++;
      if (ch === '}') {
        depth--;
        if (depth === 0) {
          const raw = buf.slice(objStart, i + 1);
          try {
            const parsed = JSON.parse(raw);
            if (parsed && typeof parsed === 'object') {
              const out: Record<string, number> = {};
              for (const [k, v] of Object.entries(parsed)) {
                if (typeof v === 'number') out[k] = Number(v || 0);
                else if (v && typeof v === 'object' && 'rows' in (v as any)) out[k] = Number((v as any).rows || 0);
                else out[k] = 0;
              }
              return out;
            }
          } catch {
            // keep reading more chunks
          }
        }
      }
    }

    if (started && objStart > 0 && buf.length > 1024 * 1024) {
      buf = buf.slice(objStart);
      objStart = 0;
    }
  }
  return null;
}

export async function* iterBackupRowsFromStream(stream: ReadableStream<Uint8Array>, gzip?: boolean) {
  const skipWS = (buf: string, i: number) => {
    while (i < buf.length) {
      const c = buf[i];
      if (c === " " || c === "\n" || c === "\r" || c === "\t") i++;
      else break;
    }
    return i;
  };

  const readJsonString = (buf: string, i: number) => {
    i++; // skip opening quote
    let out = "";
    let esc = false;
    while (i < buf.length) {
      const c = buf[i++];
      if (esc) {
        out += c;
        esc = false;
        continue;
      }
      if (c === "\\") {
        out += c;
        esc = true;
        continue;
      }
      if (c === '"') {
        return { value: JSON.parse(`"${out}"`), next: i };
      }
      out += c;
    }
    return null;
  };

  let buf = "";
  let state: "seek_tables" | "seek_table_key" | "seek_array_start" | "in_array" = "seek_tables";
  let curTable = "";

  let objStart = -1;
  let depth = 0;
  let objInString = false;
  let objEscape = false;

  for await (const chunk of textChunksFromStream(stream, gzip)) {
    buf += chunk;
    let i = 0;

    while (i < buf.length) {
      if (state === "seek_tables") {
        const idx = buf.indexOf('"tables"', i);
        if (idx === -1) {
          buf = buf.slice(Math.max(0, buf.length - 64));
          i = 0;
          break;
        }
        i = idx + '"tables"'.length;
        i = skipWS(buf, i);
        if (buf[i] !== ":") { i++; continue; }
        i++;
        i = skipWS(buf, i);
        if (buf[i] !== "{") { i++; continue; }
        i++;
        state = "seek_table_key";
        continue;
      }

      if (state === "seek_table_key") {
        i = skipWS(buf, i);
        if (i >= buf.length) break;
        if (buf[i] === "}") return;
        if (buf[i] === ",") { i++; continue; }
        if (buf[i] !== '"') { i++; continue; }

        const r = readJsonString(buf, i);
        if (!r) break;
        curTable = r.value;
        i = r.next;
        state = "seek_array_start";
        continue;
      }

      if (state === "seek_array_start") {
        i = skipWS(buf, i);
        if (i >= buf.length) break;
        if (buf[i] !== ":") { i++; continue; }
        i++;
        i = skipWS(buf, i);
        if (i >= buf.length) break;
        if (buf[i] !== "[") { i++; continue; }
        i++;
        state = "in_array";
        objStart = -1;
        depth = 0;
        objInString = false;
        objEscape = false;
        continue;
      }

      if (state === "in_array") {
        i = skipWS(buf, i);
        if (i >= buf.length) break;

        const c = buf[i];

        if (objStart === -1) {
          if (c === "]") {
            i++;
            state = "seek_table_key";
            continue;
          }
          if (c === ",") { i++; continue; }
          if (c === "{") {
            objStart = i;
            depth = 0;
            objInString = false;
            objEscape = false;
          } else {
            i++;
            continue;
          }
        }

        for (; i < buf.length; i++) {
          const ch = buf[i];

          if (objInString) {
            if (objEscape) {
              objEscape = false;
              continue;
            }
            if (ch === "\\") {
              objEscape = true;
              continue;
            }
            if (ch === '"') {
              objInString = false;
              continue;
            }
            continue;
          } else {
            if (ch === '"') {
              objInString = true;
              continue;
            }
            if (ch === "{") depth++;
            if (ch === "}") {
              depth--;
              if (depth === 0) {
                const rowText = buf.slice(objStart, i + 1);
                yield { table: curTable, rowText };
                objStart = -1;
                i++;
                break;
              }
            }
          }
        }

        if (objStart !== -1) {
          buf = buf.slice(objStart);
          i = 0;
          objStart = 0;
          break;
        }

        if (i > 4096) {
          buf = buf.slice(i);
          i = 0;
        }
        continue;
      }

      i++;
    }
  }
}

// Iterate table keys under top-level "tables" object, even when the table array is empty.
// This lets UI distinguish between "table not included in backup" vs "included but 0 rows".
export async function* iterBackupTableKeysFromStream(stream: ReadableStream<Uint8Array>, gzip?: boolean) {
  const skipWS = (buf: string, i: number) => {
    while (i < buf.length) {
      const c = buf[i];
      if (c === " " || c === "\n" || c === "\r" || c === "\t") i++;
      else break;
    }
    return i;
  };

  const readJsonString = (buf: string, i: number) => {
    i++; // skip opening quote
    let out = "";
    let esc = false;
    while (i < buf.length) {
      const c = buf[i++];
      if (esc) {
        out += c;
        esc = false;
        continue;
      }
      if (c === "\\") {
        out += c;
        esc = true;
        continue;
      }
      if (c === '"') {
        return { value: JSON.parse(`"${out}"`), next: i };
      }
      out += c;
    }
    return null;
  };

  let buf = "";
  let state: "seek_tables" | "seek_table_key" | "seek_array_start" = "seek_tables";
  const yielded = new Set<string>();

  for await (const chunk of textChunksFromStream(stream, gzip)) {
    buf += chunk;
    let i = 0;

    while (i < buf.length) {
      if (state === "seek_tables") {
        const idx = buf.indexOf('"tables"', i);
        if (idx === -1) {
          buf = buf.slice(Math.max(0, buf.length - 64));
          i = 0;
          break;
        }
        i = idx + '"tables"'.length;
        i = skipWS(buf, i);
        if (buf[i] !== ":") { i++; continue; }
        i++;
        i = skipWS(buf, i);
        if (buf[i] !== "{") { i++; continue; }
        i++;
        state = "seek_table_key";
        continue;
      }

      if (state === "seek_table_key") {
        i = skipWS(buf, i);
        if (i >= buf.length) break;
        if (buf[i] === "}") return;
        if (buf[i] === ",") { i++; continue; }
        if (buf[i] !== '"') { i++; continue; }

        const r = readJsonString(buf, i);
        if (!r) break;
        const table = r.value;
        if (table && !yielded.has(table)) {
          yielded.add(table);
          yield table;
        }
        i = r.next;
        state = "seek_array_start";
        continue;
      }

      if (state === "seek_array_start") {
        i = skipWS(buf, i);
        if (i >= buf.length) break;
        if (buf[i] !== ":") { i++; continue; }
        i++;
        i = skipWS(buf, i);
        if (i >= buf.length) break;
        if (buf[i] !== "[") { i++; continue; }

        let depth = 0;
        let inStr = false;
        let esc = false;
        for (; i < buf.length; i++) {
          const ch = buf[i];
          if (inStr) {
            if (esc) { esc = false; continue; }
            if (ch === "\\") { esc = true; continue; }
            if (ch === '"') { inStr = false; continue; }
            continue;
          }
          if (ch === '"') { inStr = true; continue; }
          if (ch === "[") depth++;
          if (ch === "]") {
            depth--;
            if (depth === 0) { i++; break; }
          }
        }

        if (depth !== 0) {
          buf = buf.slice(Math.max(0, i - 4096));
          i = 0;
          break;
        }
        state = "seek_table_key";
        continue;
      }

      i++;
    }
  }
}
