<template><el-card class="asset-page-card"><PcAssetsToolbar v-model:status="status" v-model:keyword="keyword" :is-admin="isAdmin" :can-operator="canOperator" @search="onSearch" @reset="reset" @export="exportExcel" @init-qr="initQrKeys" @download-template="downloadAssetTemplate" @import-file="onImportAssetsFile" /><PcAssetsTable :rows="rows" :loading="loading" :page="page" :page-size="pageSize" :total="total" :can-operator="canOperator" :is-admin="isAdmin" @open-info="openInfo" @open-edit="openEdit" @open-qr="openQr" @remove="removeAsset" @page-change="(value) => onPageChange(currentFilters(), value)" @page-size-change="(value) => onPageSizeChange(currentFilters(), value)" /><PcAssetEditDialog v-model:visible="editVisible" :form="editForm" :saving="saving" @save="saveEdit" /><PcAssetInfoDialog v-model:visible="infoVisible" :row="infoRow" /><PcAssetQrDialog v-model:visible="qrVisible" :loading="qrLoading" :data-url="qrDataUrl" :link="qrLink" :row="qrRow" :is-admin="isAdmin" :status-text="statusText" @download-qr="downloadQr" @download-label="downloadLabel" @open-link="openQrInNewTab" @copy-link="copyQrLink" @reset-qr="resetQr" /></el-card></template>
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { apiDelete, apiGet, apiPost, apiPut } from '../api/client';
import { usePagedAssetList } from '../composables/usePagedAssetList';
import { downloadTemplate, exportToXlsx, parseXlsx } from '../utils/excel';
import { formatBeijingDateTime } from '../utils/datetime';
import { can } from '../store/auth';
import QRCode from 'qrcode';
import PcAssetsToolbar from '../components/assets/PcAssetsToolbar.vue';
import PcAssetsTable from '../components/assets/PcAssetsTable.vue';
import PcAssetEditDialog from '../components/assets/PcAssetEditDialog.vue';
import PcAssetInfoDialog from '../components/assets/PcAssetInfoDialog.vue';
import PcAssetQrDialog from '../components/assets/PcAssetQrDialog.vue';

type PcAsset = Record<string, any>; type PcFilters = { status: string; keyword: string };
function statusText(s: string) { if (s==='IN_STOCK') return '在库'; if (s==='ASSIGNED') return '已领用'; if (s==='RECYCLED') return '已回收'; if (s==='SCRAPPED') return '已报废'; return s || '-'; }
const status = ref(''); const keyword = ref(''); const canOperator = computed(() => can('operator')); const isAdmin = computed(() => can('admin'));
const currentFilters = (): PcFilters => ({ status: status.value || '', keyword: keyword.value || '' });
const { rows, loading, page, pageSize, total, load, reload, onPageChange, onPageSizeChange } = usePagedAssetList<PcFilters, PcAsset>({ createFilterKey: (f) => `status=${f.status}&keyword=${f.keyword}`, fetchPage: async ({ filters, page, pageSize, fast }) => { const qs = new URLSearchParams(); if (filters.status) qs.set('status', filters.status); if (filters.keyword) qs.set('keyword', filters.keyword); qs.set('page', String(page)); qs.set('page_size', String(pageSize)); if (fast) qs.set('fast','1'); const r:any = await apiGet(`/api/pc-assets?${qs.toString()}`); return { rows: r.data || [], total: typeof r.total === 'number' ? Number(r.total) : null }; }, fetchTotal: async (filters) => { const qs = new URLSearchParams(); if (filters.status) qs.set('status', filters.status); if (filters.keyword) qs.set('keyword', filters.keyword); const r:any = await apiGet(`/api/pc-assets-count?${qs.toString()}`); return Number(r.total || 0); } });
const editVisible = ref(false); const saving = ref(false); const editForm = ref<PcAsset>({ id:0, brand:'', model:'', serial_no:'', manufacture_date:'', warranty_end:'', disk_capacity:'', memory_size:'', remark:'' }); const infoVisible = ref(false); const infoRow = ref<PcAsset|null>(null); const qrVisible = ref(false); const qrLoading = ref(false); const qrDataUrl = ref(''); const qrLink = ref(''); const qrRow = ref<PcAsset|null>(null);
const onSearch = () => reload(currentFilters()); const reset = () => { status.value=''; keyword.value=''; reload(currentFilters()); };
async function initQrKeys(){try{await ElMessageBox.confirm('将为所有缺少二维码Key的电脑批量生成Key（分批执行）。继续？','初始化二维码Key',{type:'warning'}); loading.value=true; let totalUpdated=0; for(let i=0;i<20;i+=1){const r:any=await apiPost('/api/pc-assets-init-qr-keys?batch=200',{}); const n=Number(r?.updated||0); totalUpdated+=n; if(!n) break;} ElMessage.success(totalUpdated?`已补齐 ${totalUpdated} 台电脑的二维码Key`:'无需补齐（都已存在）');}catch(e:any){ if(e?.message) ElMessage.error(e.message);} finally{loading.value=false;}}
async function openQr(row: PcAsset){ qrRow.value=row; qrVisible.value=true; qrLoading.value=true; qrDataUrl.value=''; qrLink.value=''; try{ const r:any=await apiGet(`/api/pc-asset-qr-token?id=${encodeURIComponent(String(row.id))}`); qrLink.value=r.url; qrDataUrl.value=await QRCode.toDataURL(r.url,{ width:260, margin:3, errorCorrectionLevel:'Q' }); }catch(e:any){ ElMessage.error(e?.message||'生成二维码失败'); qrVisible.value=false; }finally{ qrLoading.value=false; } }
async function resetQr(){ try{ if(!qrRow.value?.id) return; await ElMessageBox.confirm('确认要重置该电脑的二维码吗？重置后旧二维码将立即失效。','重置二维码',{type:'warning'}); qrLoading.value=true; const r:any=await apiPost(`/api/pc-assets-reset-qr?id=${encodeURIComponent(String(qrRow.value.id))}`,{}); qrLink.value=r.url; qrDataUrl.value=await QRCode.toDataURL(r.url,{ width:260, margin:3, errorCorrectionLevel:'Q' }); ElMessage.success('已重置，新二维码已生成'); }catch(e:any){ if(e?.message) ElMessage.error(e.message); }finally{ qrLoading.value=false; } }
async function copyQrLink(){ try{ if(!qrLink.value) return; await navigator.clipboard.writeText(qrLink.value); ElMessage.success('已复制'); }catch{ const ta=document.createElement('textarea'); ta.value=qrLink.value; document.body.appendChild(ta); ta.select(); document.execCommand('copy'); ta.remove(); ElMessage.success('已复制'); } }
function mmToPx(mm:number, dpi=300){ return Math.round((mm/25.4)*dpi); }
function downloadLabel(){ if(!qrLink.value) return; const row=qrRow.value||{}; const title=`${row.brand||''} ${row.model||''}`.trim()||'电脑信息'; const sn=(row.serial_no||row.id||'').toString(); const W=mmToPx(50); const H=mmToPx(30); const canvas=document.createElement('canvas'); canvas.width=W; canvas.height=H; const ctx=canvas.getContext('2d'); if(!ctx) return; ctx.fillStyle='#fff'; ctx.fillRect(0,0,W,H); const pad=Math.round(W*0.04); const topH=Math.round(H*0.22); const bottomH=Math.round(H*0.18); ctx.fillStyle='#111'; ctx.textBaseline='middle'; ctx.font=`bold ${Math.round(H*0.12)}px sans-serif`; const maxTitleW=W-pad*2; let t=title; while(ctx.measureText(t).width>maxTitleW && t.length>6) t=t.slice(0,-1); if(t!==title) t+='…'; ctx.fillText(t,pad,Math.round(topH/2)); const qrAreaTop=topH; const qrAreaH=H-topH-bottomH; const qrSize=Math.min(qrAreaH,Math.round(W*0.52)); const qrX=Math.round((W-qrSize)/2); const qrY=qrAreaTop+Math.round((qrAreaH-qrSize)/2); QRCode.toDataURL(qrLink.value,{ width:qrSize, margin:3, errorCorrectionLevel:'Q' }).then((dataUrl:string)=>{ const img=new Image(); img.onload=()=>{ ctx.drawImage(img,qrX,qrY,qrSize,qrSize); ctx.fillStyle='#111'; ctx.font=`${Math.round(H*0.11)}px monospace`; const bottomY=H-Math.round(bottomH/2); const snText=sn?`SN: ${sn}`:''; const tw=ctx.measureText(snText).width; ctx.fillText(snText, Math.max(pad, Math.round((W-tw)/2)), bottomY); const a=document.createElement('a'); const name=(sn||row.id||'pc').toString(); a.download=`PC_${name}_标签_50x30mm.png`; a.href=canvas.toDataURL('image/png'); document.body.appendChild(a); a.click(); a.remove(); }; img.src=dataUrl; }).catch(()=>ElMessage.error('生成标签失败')); }
function downloadQr(){ if(!qrDataUrl.value) return; const a=document.createElement('a'); const sn=(qrRow.value?.serial_no||qrRow.value?.id||'pc').toString(); a.download=`PC_${sn}_二维码.png`; a.href=qrDataUrl.value; document.body.appendChild(a); a.click(); a.remove(); }
const openQrInNewTab = () => { if(qrLink.value) window.open(qrLink.value,'_blank'); };
function openEdit(row: PcAsset){ editForm.value={ id:row.id, brand:row.brand||'', model:row.model||'', serial_no:row.serial_no||'', manufacture_date:row.manufacture_date||'', warranty_end:row.warranty_end||'', disk_capacity:row.disk_capacity||'', memory_size:row.memory_size||'', remark:row.remark||'' }; editVisible.value=true; }
function openInfo(row: PcAsset){ infoRow.value={...row}; infoVisible.value=true; }
async function saveEdit(){ const f=editForm.value||{}; if(!String(f.brand||'').trim()) return ElMessage.warning('品牌必填'); if(!String(f.model||'').trim()) return ElMessage.warning('型号必填'); if(!String(f.serial_no||'').trim()) return ElMessage.warning('序列号必填'); try{ saving.value=true; await apiPut('/api/pc-assets', f); ElMessage.success('修改成功'); editVisible.value=false; await load(currentFilters(),{ keepPage:true }); }catch(e:any){ ElMessage.error(e?.message||'修改失败'); }finally{ saving.value=false; } }
async function removeAsset(row: PcAsset){ try{ await ElMessageBox.confirm(`确认删除电脑台账：${row.brand||''} ${row.model||''}（SN: ${row.serial_no||'-'}）？`,'删除确认',{ type:'warning', confirmButtonText:'确认删除', cancelButtonText:'取消' }); loading.value=true; await apiDelete('/api/pc-assets',{ id: row.id }); ElMessage.success('删除成功'); if(rows.value.length===1 && page.value>1) page.value-=1; await load(currentFilters(),{ keepPage:true }); }catch(e:any){ if(e==='cancel' || e==='close') return; ElMessage.error(e?.message||'删除失败'); }finally{ loading.value=false; } }
async function fetchAll(){ const all:PcAsset[]=[]; let p=1; let totalLocal=0; do{ const qs=new URLSearchParams(); if(status.value) qs.set('status',status.value); if(keyword.value) qs.set('keyword',keyword.value); qs.set('page',String(p)); qs.set('page_size','200'); const r:any=await apiGet(`/api/pc-assets?${qs.toString()}`); const list=r?.data||[]; totalLocal=Number(r?.total||0); all.push(...list); p+=1; if(all.length>=totalLocal) break; }while(p<999); return all; }
async function exportExcel(){ try{ loading.value=true; const all=await fetchAll(); exportToXlsx({ filename:'电脑台账_仓库2.xlsx', sheetName:'台账', headers:[{key:'id',title:'ID'},{key:'status',title:'状态'},{key:'brand',title:'品牌'},{key:'serial_no',title:'序列号'},{key:'model',title:'型号'},{key:'manufacture_date',title:'出厂时间'},{key:'warranty_end',title:'保修到期'},{key:'disk_capacity',title:'硬盘容量'},{key:'memory_size',title:'内存大小'},{key:'remark',title:'备注'},{key:'created_at',title:'创建时间'},{key:'updated_at',title:'更新时间'}], rows: all.map((r)=>({ ...r, created_at: formatBeijingDateTime(r.created_at), updated_at: formatBeijingDateTime(r.updated_at) })) }); }catch(e:any){ ElMessage.error(e?.message||'导出失败'); }finally{ loading.value=false; } }
function downloadAssetTemplate(){ downloadTemplate({ filename:'电脑台账导入模板.xlsx', headers:[{title:'品牌'},{title:'序列号'},{title:'型号'},{title:'出厂时间'},{title:'保修到期'},{title:'硬盘容量'},{title:'内存大小'},{title:'备注'}], exampleRows:[{品牌:'Dell',序列号:'SN123456',型号:'Latitude 5440',出厂时间:'2024-01-01',保修到期:'2027-01-01',硬盘容量:'512G',内存大小:'16G',备注:'示例，可删除该行'}] }); }
async function onImportAssetsFile(uploadFile:any){ const file:File=uploadFile?.raw; if(!file) return; try{ const rows=await parseXlsx(file); const items=rows.map((r)=>({ brand:String(r['品牌']??r.brand??'').trim(), serial_no:String(r['序列号']??r.serial_no??'').trim(), model:String(r['型号']??r.model??'').trim(), manufacture_date:String(r['出厂时间']??r.manufacture_date??'').trim(), warranty_end:String(r['保修到期']??r.warranty_end??'').trim(), disk_capacity:String(r['硬盘容量']??r.disk_capacity??'').trim(), memory_size:String(r['内存大小']??r.memory_size??'').trim(), remark:String(r['备注']??r.remark??'').trim() })).filter((x)=>x.brand||x.serial_no||x.model); if(!items.length) return ElMessage.warning('Excel里没有可导入的数据'); const missing=items.map((it,idx)=>({idx,v:String(it.manufacture_date||'').trim()})).filter((x)=>!x.v).slice(0,15).map((x)=>x.idx+2); if(missing.length) return ElMessage.warning(`出厂时间必填，缺失行号：${missing.join(', ')}${missing.length>=15?' …':''}`); const res:any=await apiPost('/api/pc-in-batch',{ items }); const failed=Number(res?.failed||0); if(failed>0){ ElMessage.warning(`导入完成：成功 ${res.success} 条，失败 ${failed} 条（请查看控制台/接口返回 errors）`); console.warn('pc-in-batch errors',res?.errors); }else{ ElMessage.success(`导入完成：成功 ${res.success} 条`); } await load(currentFilters(),{ keepPage:true }); }catch(e:any){ ElMessage.error(e?.message||'导入失败'); } }
onMounted(()=>{ load(currentFilters()); });
</script>
<style scoped>.asset-page-card{border-radius:18px}</style>
